import "./globals.css";
import { css } from "../../styled-system/css";
import type { Metadata } from "next";
import { Footer } from "../components/footer";
import "highlight.js/styles/github-dark-dimmed.css";

// const geistSans = localFont({
// 	src: './fonts/GeistVF.woff',
// 	variable: '--font-geist-sans',
// 	weight: '100 900',
// });
// const geistMono = localFont({
// 	src: './fonts/GeistMonoVF.woff',
// 	variable: '--font-geist-mono',
// 	weight: '100 900',
// });

export const metadata: Metadata = {
	title: "nomanoma121",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={css({
					backgroundColor: "background",
				})}
			>
				{children}
			</body>
			<Footer />
		</html>
	);
}
